# A sample Gemfile
source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-org', group: :jekyll_plugins

group :development do
  gem 'foreman'
  gem 'guard'
  gem 'guard-livereload'
end
